image: docker-registry.sensorberg.io/devops/dockerimages/python-test:1.0.1
variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - test
  - build
  
test:
  stage: test
  script:
    - python -m unittest discover
    
build:
  stage: build
  script:
    - python setup.py sdist
    - pip install twine
    - twine upload --repository-url https://python.infrastructure.dev.sensorberg-cloud.com/ dist/*